services:
  deeprelay:
    image: lingyuanzhicheng/deeprelay
    ports:
       - '8080:8080'
    volumes:      
       - '/path/to/data:/app/data'
    container_name: deeprelay
    restart: unless-stopped